
{
    "openapi": "3.0.0",
    "servers": [
      {
        "description": "Serveur de production du blog",
        "url": "https://ns-blog-api.herokuapp.com"
      },
      {
        "description": "Serveur de test",
        "url": "http://localhost:3333"
      }
    ],
    "info": {
      "title": "NS Blog api",
      "version": "1.0.0",
      "description": "Il s'agit de mon api de blog",
      "contact": {
        "name": "Wilfried N'SOUKPOE",
        "email": "wacnsoukpoe@gmail.com"
      }
    },
    "paths": {
      "/comments": {
        "get": {
          "tags": [
            "Comment"
          ],
          "summary": "Récupérer",
          "description": "Récupérer tous les commentaires du blog",
          "parameters": [
            
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Tous les commenaires du blog",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "example": {
                        "id": 2,
                        "message": "Je suis un commentaire",
                        "post_id": "post-random",
                        "user_id": 1,
                        "created_at": "2022-06-05",
                        "updated_at": "2022-06-05"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/comments/{id}": {
        "get": {
          "tags": [
            "Comment"
          ],
          "summary": "Récupérer",
          "description": "Récupérer un commentaire en particulier",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "commentId",
              "in": "path",
              "description": "ID du commentaire",
              "required": true,
              "schema": {
                "type": "integer"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Succès",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "id": 2,
                      "message": "Je suis un commentaire",
                      "post_id": "post-random",
                      "user_id": 1,
                      "created_at": "2022-09-03T17:36:12.702+00:00",
                      "updated_at": "2022-09-03T17:36:12.702+00:00"
                    }
                  }
                }
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Comment"
          ],
          "summary": "Supprimer",
          "description": "Supprimer un commentaire",
          "parameters": [
            {
              "name": "commentId",
              "in": "path",
              "description": "ID du commentaire",
              "required": true,
              "schema": {
                "type": "integer"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Commentaire supprimé",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "status": "OK",
                      "message": "Commentaire supprimé"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/posts": {
        "get": {
          "tags": [
            "Post"
          ],
          "summary": "Récupérer",
          "description": "Récupérer tous les posts du blog",
          "parameters": [
            
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Tous les posts du blog",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "example": {
                        "id": 2,
                        "name": "Post random",
                        "description": "Je suis une description courte",
                        "content": "Je suis une descrption longue",
                        "thumbnail": "https://googlehearth.com/",
                        "slug": "post-random",
                        "user_id": 1,
                        "created_at": "2022-09-03T17:36:12.702+00:00",
                        "updated_at": "2022-09-03T17:36:12.702+00:00"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/posts/{id}": {
        "get": {
          "tags": [
            "Post"
          ],
          "summary": "Récupérer",
          "description": "Récupérer un post en particulier",
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "postId",
              "in": "path",
              "description": "ID du post",
              "required": true,
              "schema": {
                "type": "integer"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Succès",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "id": 2,
                      "name": "Post random",
                      "description": "Je suis une description courte",
                      "content": "Je suis une descrption longue",
                      "thumbnail": "https://googlehearth.com/",
                      "slug": "post-random",
                      "user_id": 1,
                      "created_at": "2022-09-03T17:36:12.702+00:00",
                      "update_at": "2022-09-03T17:36:12.702+00:00"
                    }
                  }
                }
              }
            }
          }
        },
        "put": {
          "tags": [
            "Post"
          ],
          "summary": "Modifier",
          "description": "Modifier le post",
          "parameters": [
            {
              "name": "postId",
              "required": true,
              "in": "path",
              "description": "ID du post",
              "schema": {
                "type": "integer"
              }
            },
            {
              "name": "Informations du post",
              "in": "body",
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Random2",
                  "required": false
                },
                "description": {
                  "type": "string",
                  "required": false
                },
                "content": {
                  "type": "string",
                  "required": false
                },
                "thumbnail": {
                  "type": "string",
                  "required": false
                }
              }
            }
          ],
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "status": "OK",
                      "message": "Post bien modifié"
                    }
                  }
                }
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Post"
          ],
          "summary": "Supprimer",
          "description": "Supprimer un post",
          "parameters": [
            {
              "name": "postId",
              "in": "path",
              "description": "ID du post",
              "required": true,
              "schema": {
                "type": "integer"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Post supprimé",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "status": "OK",
                      "message": "Post supprimé"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/user/register": {
        "post": {
          "tags": [
            "Auth"
          ],
          "summary": "Inscription",
          "security": [
            
          ],
          "description": "Enregistrer un  utilisateur par ses informations",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "email": "random@gmail.com",
                    "password": "random",
                    "username": "random"
                  }
                }
              }
            }
          },
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Utilisateur bien enregistré"
            },
            "500": {
              "description": "Erreur au niveau du serveur"
            }
          }
        }
      },
      "/user/login": {
        "post": {
          "tags": [
            "Auth"
          ],
          "summary": "Connexion",
          "security": [
            
          ],
          "description": "Connecter un  utilisateur",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "email": "random@gmail.com",
                    "password": "random"
                  }
                }
              }
            }
          },
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "username": "hello"
                    }
                  }
                }
              }
            },
            "500": {
              "description": "Erreur au niveau du serveur"
            }
          }
        }
      },
      "/users": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Récupération",
          "description": "Récupérer tous les utilisateurs connectés",
          "parameters": [
            
          ],
          "produces": [
            "application/json"
          ],
          "responses": {
            "200": {
              "description": "Succès",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "example": {
                        "id": 1,
                        "username": "Random",
                        "email": "random@gmail.com",
                        "profile": null,
                        "remember_token": null,
                        "created_at": "2022-03-03"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/user/{id}": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Récupérer un utilisateur",
          "description": "Récupérer un seul utilisateur",
          "parameters": [
            {
              "name": "userId",
              "description": "ID de l'utilisateur",
              "required": true,
              "schema": {
                "type": "integer"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Succès",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "example": {
                      "id": 1,
                      "username": "Random",
                      "email": "random@gmail.com",
                      "profile": null,
                      "created_at": "2022-03-11",
                      "remember_me_token": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      
    },
    "tags": [
      
    ]
  }